import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import os from 'node:os';
const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'dlcj-home-qa-'));
const requireQA = createRequire(path.join(process.env.STORE_UI_QA_DIR || repo, 'package.json'));
const requireRepo = createRequire(repo + '/package.json');
const { JSDOM } = requireQA('jsdom');
const { buildSync } = requireQA('esbuild');
const dom = new JSDOM('<!doctype html><div id="root"></div>', { url: 'https://example.test/', pretendToBeVisual: true });
Object.assign(global, { window: dom.window, document: dom.window.document, HTMLElement: dom.window.HTMLElement, Node: dom.window.Node, IS_REACT_ACT_ENVIRONMENT: true });
Object.defineProperty(global, 'navigator', { value: dom.window.navigator, configurable: true });
let reduced = false;
const motionListeners = new Set();
window.matchMedia = () => ({ matches: reduced, addEventListener: (_, fn) => motionListeners.add(fn), removeEventListener: (_, fn) => motionListeners.delete(fn) });
let visible = true;
Object.defineProperty(document, 'visibilityState', { get: () => visible ? 'visible' : 'hidden' });
const intervals = new Map(); let intervalID = 0;
window.setInterval = (fn, delay) => { const id = ++intervalID; intervals.set(id, { fn, delay }); return id; };
window.clearInterval = id => intervals.delete(id);
buildSync({ entryPoints: [repo + '/components/store-home.tsx'], bundle: true, platform: 'node', format: 'cjs', outfile: path.join(tmp, 'component.cjs'), alias: { '@': repo, react: repo + '/node_modules/react' }, external: [repo + '/node_modules/react/*', repo + '/node_modules/react'], jsx: 'automatic' });
const React = requireRepo('react');
const { act } = React;
const { createRoot } = requireRepo('react-dom/client');
const StoreHome = requireRepo(path.join(tmp, 'component.cjs')).default;
const root = createRoot(document.getElementById('root'));
const tests = [];
const check = (name, fn) => { fn(); tests.push(name); };
const $ = s => document.querySelector(s);
const current = () => $('.sh-productCopy h2').textContent;
const active = () => [...document.querySelectorAll('.sh-slide')].findIndex(el => el.dataset.active === 'true');
const click = s => act(() => $(s).click());
const key = key => act(() => $('.sh-stage').dispatchEvent(new window.KeyboardEvent('keydown', { key, bubbles: true })));
const touch = (name, x, y) => { const e = new window.Event(name, { bubbles: true }); Object.defineProperty(e, name === 'touchstart' ? 'touches' : 'changedTouches', { value: [{ clientX: x, clientY: y }] }); return e; };

act(() => root.render(React.createElement(StoreHome, { lang: 'zh' })));
check('Seven photo slides, one accessible active slide, no inactive focus targets', () => {
 assert.equal(document.querySelectorAll('.sh-slide').length, 7);
 assert.equal(document.querySelectorAll('.sh-slide[aria-hidden="true"]').length, 6);
 assert.equal(document.querySelectorAll('.sh-slide a, .sh-slide button, .sh-slide [tabindex]').length, 0);
 assert.equal(active(), 0);
 assert.equal($('.sh-photoExample img').getAttribute('src'), '/products/black-coral-800.webp');
 assert.ok(!document.querySelector('canvas'));
});
check('Autoplay has a 4500ms interval', () => { assert.equal(intervals.size, 1); assert.equal([...intervals.values()][0].delay, 4500); });
act(() => [...intervals.values()][0].fn());
check('Automatic slide updates product title and checkout selection', () => { assert.equal(active(), 1); assert.equal(current(), '曜石 · 珊瑚红'); assert.equal($('.sh-buy a').getAttribute('href'), '/checkout?style=black-coral'); });
act(() => { const event = new window.MouseEvent('pointerover', { bubbles: true }); Object.defineProperty(event, 'pointerType', { value: 'mouse' }); $('.sh-carousel').dispatchEvent(event); });
check('Mouse hover pauses autoplay', () => assert.equal(intervals.size, 0));
act(() => { const event = new window.MouseEvent('pointerout', { bubbles: true }); Object.defineProperty(event, 'pointerType', { value: 'mouse' }); $('.sh-carousel').dispatchEvent(event); });
check('Mouse leave resumes allowed autoplay', () => assert.equal(intervals.size, 1));
act(() => $('.sh-stage').focus());
check('Keyboard focus pauses autoplay', () => assert.equal(intervals.size, 0));
act(() => $('.sh-stage').blur());
check('Leaving focus resumes the unmodified slideshow', () => assert.equal(intervals.size, 1));
click('.sh-arrowNext');
check('Explicit selection pauses autoplay persistently', () => { assert.equal(active(), 2); assert.equal(intervals.size, 0); assert.equal($('.sh-play').getAttribute('aria-label'), '播放自动轮播'); });
key('End'); check('End selects final style', () => assert.equal(active(), 6));
key('ArrowRight'); check('Right arrow wraps last to first', () => assert.equal(active(), 0));
key('ArrowLeft'); check('Left arrow wraps first to last', () => assert.equal(active(), 6));
key('Home'); check('Home selects first style', () => assert.equal(active(), 0));
click('.sh-dots button:nth-child(5)');
check('Dots select exact style and update checkout', () => { assert.equal(active(), 4); assert.equal($('.sh-buy a').getAttribute('href'), '/checkout?style=diamond-ivory'); });
act(() => { $('.sh-stage').dispatchEvent(touch('touchstart', 250, 100)); $('.sh-stage').dispatchEvent(touch('touchend', 150, 110)); });
check('Horizontal swipe selects next style', () => assert.equal(active(), 5));
act(() => { $('.sh-stage').dispatchEvent(touch('touchstart', 250, 100)); $('.sh-stage').dispatchEvent(touch('touchend', 245, 210)); });
check('Vertical gesture does not switch styles', () => assert.equal(active(), 5));
click('.sh-play');
check('Explicit play restarts autoplay', () => assert.equal(intervals.size, 1));
act(() => { visible = false; document.dispatchEvent(new window.Event('visibilitychange')); });
check('Hidden document pauses autoplay', () => assert.equal(intervals.size, 0));
act(() => { visible = true; document.dispatchEvent(new window.Event('visibilitychange')); });
check('Visible document restarts allowed autoplay', () => assert.equal(intervals.size, 1));
act(() => { reduced = true; motionListeners.forEach(fn => fn()); });
check('Reduced motion stops autoplay and disables its start button', () => { assert.equal(intervals.size, 0); assert.equal($('.sh-play').disabled, true); });
click('.sh-arrowNext'); check('Manual navigation remains available with reduced motion', () => assert.equal(active(), 6));
click('[aria-controls="sh-contact"]');
check('Contact disclosure opens with actual contact methods', () => { assert.equal($('#sh-contact').hidden, false); assert.match($('#sh-contact').textContent, /13859235588/); assert.match($('#sh-contact').textContent, /Zjw123098/); });
click('[aria-controls="sh-terms"]');
check('Purchase disclosure contains correct durations/material/shipping boundaries', () => { assert.equal($('#sh-contact').hidden, true); assert.equal($('#sh-terms').hidden, false); const text=$('#sh-terms').textContent; for(const part of ['细纹皮', '1–2 个自然日', '5–7 个自然日', '包含周末', '运输时间另计', '运费按地址另行确认']) assert.ok(text.includes(part), part); });
click('#sh-terms .sh-informationHeading button');
check('Closing disclosure restores trigger focus', () => { assert.equal($('#sh-terms').hidden, true); assert.equal(document.activeElement.getAttribute('aria-controls'), 'sh-terms'); });
check('Navigation points at approved routes', () => { assert.ok($('.sh-nav a[href="/my"]')); assert.ok($('.sh-nav a[href="/customize"]')); assert.ok($('.sh-footer a[href="/gallery"]')); });
act(() => root.render(React.createElement(StoreHome, { lang: 'en' })));
check('English version remains complete', () => { assert.equal($('.sh-home').lang, 'en'); assert.equal($('.sh-intro h1').textContent, 'A little detail. Entirely you.'); assert.match($('#sh-terms').textContent, /Weekends are included/); });
act(() => root.unmount());
check('Unmount clears timers and subscriptions', () => { assert.equal(intervals.size, 0); assert.equal(motionListeners.size, 0); });
const report = { date: new Date().toISOString(), result: 'PASS', checks: tests.length, tests, limits: ['DOM-level assertions only; live browser rendering blocked by local Chromium socket permission and cloud browser ERR_BLOCKED_BY_CLIENT for loopback.'] };
fs.writeFileSync(path.join(os.tmpdir(), 'dlcj-home-interactions-result.json'), JSON.stringify(report, null, 2));
console.log(JSON.stringify(report, null, 2));

dom.window.close();
fs.rmSync(tmp, {recursive:true,force:true});
