/**
 * Store UI interaction regression suite. No live server, provider, credentials or network.
 * Optional QA dependencies: jsdom and esbuild, outside production dependencies.
 * Run: STORE_UI_QA_DIR=/tmp/dlcj-qa node scripts/qa/store-ui.mjs
 */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {webcrypto} from 'node:crypto';

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const requireRepo = createRequire(path.join(repo, 'package.json'));
const requireQA = process.env.STORE_UI_QA_DIR ? createRequire(path.resolve(process.env.STORE_UI_QA_DIR, 'package.json')) : requireRepo;
let JSDOM, buildSync;
try { ({JSDOM} = requireQA('jsdom')); ({buildSync} = requireQA('esbuild')); }
catch { throw new Error('Install optional QA-only packages jsdom and esbuild, or set STORE_UI_QA_DIR to their containing project directory. See scripts/qa/README.md.'); }
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'dlcj-store-ui-'));
const dom = new JSDOM('<!doctype html><html lang="zh-CN"><body><div id="root"></div></body></html>', {url: 'https://store.example.test/', pretendToBeVisual: true});
Object.assign(globalThis, {window: dom.window, document: dom.window.document, HTMLElement: dom.window.HTMLElement, HTMLInputElement: dom.window.HTMLInputElement, Node: dom.window.Node, DOMException: dom.window.DOMException, sessionStorage: dom.window.sessionStorage, localStorage: dom.window.localStorage, IS_REACT_ACT_ENVIRONMENT: true});
Object.defineProperty(globalThis, 'navigator', {value: dom.window.navigator, configurable: true});
Object.defineProperty(globalThis, 'crypto', {value: webcrypto, configurable: true});
const realDateNow = Date.now, realClearInterval = globalThis.clearInterval;
let now = realDateNow();
Date.now = () => now;
const intervals = new Map(); let timerId = 10000;
window.setInterval = (fn, delay) => {const id = ++timerId; intervals.set(id, {fn, delay}); return id;};
window.clearInterval = id => intervals.delete(id);
globalThis.clearInterval = id => intervals.has(id) ? intervals.delete(id) : realClearInterval(id);

buildSync({stdin: {contents: `export {default as Account, StoreLogin, OrderDetail} from './components/store-account'; export {default as Checkout} from './components/store-checkout'; export {default as Admin} from './components/store-admin'; export {default as Gallery} from './components/store-gallery'; export * from './lib/store-client'; export {initialDesign} from './lib/design'; export {PrivatePhoto} from './components/store-shared';`, resolveDir: repo, loader: 'tsx'}, bundle: true, platform: 'node', format: 'cjs', outfile: path.join(tmp, 'components.cjs'), alias: {'@': repo, react: path.join(repo, 'node_modules/react')}, external: [path.join(repo, 'node_modules/react'), path.join(repo, 'node_modules/react/*')], jsx: 'automatic'});
const React = requireRepo('react');
const {act} = React;
const {createRoot} = requireRepo('react-dom/client');
const ui = createRequire(import.meta.url)(path.join(tmp, 'components.cjs'));
let root, calls = [], route;
const pass = [], failed = [];
const response = (body, status = 200) => Response.json(body, {status});
const user = {id: 'synthetic-customer', role: 'customer', phoneMasked: '138****0000'};
const session = (overrides = {}) => ({user, capabilities: {sms: true, orders: true, payment: false}, ...overrides});
const anonymous = (sms = true) => session({user: null, capabilities: {sms, orders: true, payment: false}});
const orderFixture = (overrides = {}) => ({id: 'order-synthetic', userId: user.id, kind: 'custom', product: 'tissue-box', quantity: 1, designId: 'design-synthetic', designVersion: 1, designSnapshot: ui.initialDesign(), checkout: {name: '合成测试收货人', phone: '+8613800000000', address: '合成测试地址 123 号'}, status: 'awaiting_material', currency: 'CNY', unitPriceFen: 15900, goodsTotalFen: 15900, discountFen: 500, goodsPayableFen: 15400, shippingFen: null, shippingState: 'manual_quote_required', shippingVersion: 0, acceptedShippingVersion: null, quoteVersion: 0, acceptedQuoteVersion: null, totalFen: null, materialVersion: 1, acceptedMaterialVersion: null, materials: [{version: 1, note: '合成材料版本一', photoRefs: [], createdAt: '2026-09-30T00:00:00Z'}], createdAt: '2026-09-30T00:00:00Z', updatedAt: '2026-09-30T00:00:00Z', paidAt: null, production: {startedAt: null, earliestAt: null, latestAt: null, calendarDays: [5, 7]}, shipment: null, paymentEnabled: false, ...overrides});
const designFixture = (overrides = {}) => ({id: 'design-synthetic', version: 3, name: '合成私密设计', createdAt: '2026-09-30T00:00:00Z', design: ui.initialDesign(), galleryConsent: false, galleryPublished: false, ...overrides});
const couponFixture = (overrides = {}) => ({id: 'coupon-synthetic', userId: user.id, amountFen: 5000, availableFen: 5000, spendableFen: 5000, reservedFen: 0, redeemedFen: 0, expiresAt: '2026-12-29T00:00:00Z', source: 'manual', status: 'available', ...overrides});
const deferred = () => {let resolve, reject; const promise = new Promise((a, b) => {resolve = a; reject = b;}); return {promise, resolve, reject};};
const $ = selector => document.querySelector(selector);
const text = () => document.body.textContent;
const buttons = label => [...document.querySelectorAll('button')].filter(button => button.textContent.includes(label));
const button = label => {const matches = buttons(label); assert.equal(matches.length, 1, `Expected one button containing ${label}`); return matches[0];};
const tick = () => new Promise(resolve => setImmediate(resolve));
async function flush() {await act(async () => {await tick(); await tick();});}
async function until(predicate, label) {const deadline = realDateNow() + 3000; do {await flush(); if (predicate()) return; await new Promise(resolve => setTimeout(resolve, 5));} while (realDateNow() < deadline); assert.fail('Timed out: ' + label);}
async function mount(Component, handler, url = '/', props = {}) {
  if (root) await act(async () => root.unmount());
  window.history.replaceState({}, '', url); calls = []; route = handler; sessionStorage.clear(); localStorage.clear();
  globalThis.fetch = async (input, init = {}) => {const url = String(input); const call = {path: url.replace(/^\/api\/store/, ''), method: init.method || 'GET', body: typeof init.body === 'string' ? JSON.parse(init.body) : init.body, init}; calls.push(call); const result = await route(call); if (result === undefined) throw new Error(`Unexpected mock request ${call.method} ${call.path}`); return result;};
  root = createRoot(document.getElementById('root'));
  await act(async () => root.render(React.createElement(Component, props))); await flush();
}
async function input(selector, value) {const el = $(selector); assert.ok(el, selector); const proto = el.tagName === 'TEXTAREA' ? window.HTMLTextAreaElement.prototype : window.HTMLInputElement.prototype; await act(async () => {Object.getOwnPropertyDescriptor(proto, 'value').set.call(el, value); el.dispatchEvent(new window.Event('input', {bubbles: true}));});}
async function click(el) {assert.ok(el, 'Click target exists'); await act(async () => el.click()); await flush();}
async function submit(selector = 'form') {await act(async () => $(selector).dispatchEvent(new window.Event('submit', {bubbles: true, cancelable: true}))); await flush();}
async function check(name, fn) {try {await fn(); pass.push(name); console.log('PASS ' + name);} catch (error) {failed.push({name, error: error.stack || String(error)}); console.error('FAIL ' + name + '\n' + error.stack);}}
function noPaymentAction() {assert.equal([...document.querySelectorAll('button,a')].filter(el => /^(立即支付|去付款|支付订单|确认付款|标记已付款)$/.test(el.textContent.trim())).length, 0);}
async function fillAddress() {for (const [id, value] of [['name', '合成测试收货人'], ['phone', '13800000000'], ['province', '测试省'], ['city', '测试市'], ['district', '测试区'], ['detail', '合成测试街道 123 号']]) await input('#checkout-' + id, value); const checks = [...document.querySelectorAll('input[type="checkbox"]')]; await click(checks.at(-1));}
function checkoutMock(extra = {}) {return call => {if (call.path === '/pricing') return response({pricing: {currency: 'CNY', version: 1, standardFen: 9900, customFen: 15900, updatedAt: '2026-10-03T00:00:00Z'}}); if (call.path === '/session') return response(session()); if (call.path === '/coupons') return response({coupons: extra.coupons || []}); if (call.path.startsWith('/designs/')) return response({design: extra.design || designFixture()}); if (call.path === '/orders') return extra.post?.(call);};}
function adminMock(extra = {}) {return call => {if (call.path === '/session') return response(session({user: {...user, role: 'admin'}})); if (call.path === '/admin/orders') return response({orders: extra.orders || []}); if (call.path === '/admin/designs') return response({designs: extra.designs || []}); if (call.path === '/admin/coupons' && call.method === 'GET') return response({coupons: extra.coupons || []}); if (call.path.startsWith('/admin/orders/') && call.method === 'GET') return response({order: extra.orders?.find(o => call.path.endsWith(o.id))}); return extra.other?.(call);};}
function accountMock(extra = {}) {return call => {if (call.path === '/session') return response(extra.session?.() || session()); if (call.path === '/designs') return response({designs: extra.designs || []}); if (call.path === '/orders') return response({orders: extra.orders || []}); if (call.path === '/coupons') return response({coupons: []}); if (call.path === '/referral') return response({referral: {inviteCode: 'SYNTHETIC', rewardedInvites: 0}}); return extra.other?.(call);};}

await check('Login reports disabled SMS truthfully and cannot request or verify', async () => {await mount(ui.StoreLogin, () => response(anonymous(false)), '/login?return_to=%2Fcheckout%3Fstyle%3Dblack-coral'); assert.match(text(), /短信登录暂未开通/); assert.equal(button('获取验证码').disabled, true); assert.equal(button('登录 / 注册').disabled, true); assert.equal($('.store-close').getAttribute('href'), '/checkout?style=black-coral'); assert.equal(calls.length, 1); assert.equal($('input[type="password"]'), null);});
await check('Safe return URLs reject external, protocol-relative, backslash and login loops', async () => {for (const unsafe of ['https://evil.test/', '//evil.test/', '/\\evil.test', '/login?return_to=/', '/a\r\nX:test']) assert.equal(ui.safeReturnTo(unsafe), '/my'); assert.equal(ui.safeReturnTo('/checkout?style=black-coral#review'), '/checkout?style=black-coral#review'); assert.equal(ui.loginHref('https://evil.test'), '/login?return_to=%2Fmy'); await mount(ui.StoreLogin, () => response(anonymous()), '/login?return_to=https%3A%2F%2Fevil.test'); assert.equal($('.store-close').getAttribute('href'), '/my');});
await check('Login service failure stays visible without fake login', async () => {await mount(ui.StoreLogin, () => new Response('<html>Fallback</html>', {status: 200, headers: {'content-type': 'text/html'}})); assert.match(text(), /账号与订单服务尚未接通/); assert.equal($('#login-phone'), null); assert.ok($('a[href="/customize?storage=local"]'));});
await check('Login rejects invalid phone without a provider call', async () => {await mount(ui.StoreLogin, () => response(anonymous())); await input('#login-phone', '123'); await click(button('获取验证码')); assert.match(text(), /正确的 11 位/); assert.equal(calls.filter(c => c.method === 'POST').length, 0);});
await check('OTP request prevents repeated clicks while pending and uses normalized phone', async () => {const pending = deferred(); await mount(ui.StoreLogin, call => call.path === '/session' ? response(anonymous()) : pending.promise); await input('#login-phone', '13800000000'); const send = button('获取验证码'); await act(async () => {send.click(); send.click();}); assert.equal(calls.filter(c => c.path === '/auth/otp/request').length, 1); assert.equal(calls.at(-1).body.phone, '+8613800000000'); assert.equal($('#login-phone').disabled, true); await act(async () => pending.resolve(response({challengeId: 'synthetic-otp', retryAfterSeconds: 60, expiresInSeconds: 300}))); await flush(); assert.match(text(), /验证码已发送/); assert.equal(button('60 秒后重发').disabled, true);});
await check('OTP send puts keyboard focus into the newly enabled code field', async () => {assert.ok(document.activeElement === $('#login-code'), 'Code input must receive focus after send');});
await check('Wrong OTP stays on login and unlocks retry; repeated verification is prevented', async () => {let verification; await mount(ui.StoreLogin, call => {if (call.path === '/session') return response(anonymous()); if (call.path === '/auth/otp/request') return response({challengeId: 'synthetic-otp', retryAfterSeconds: 0, expiresInSeconds: 300}); verification = deferred(); return verification.promise;}); await input('#login-phone', '13800000000'); await click(button('获取验证码')); await input('#login-code', '000000'); await act(async () => {const form = $('form'); form.dispatchEvent(new window.Event('submit', {bubbles: true, cancelable: true})); form.dispatchEvent(new window.Event('submit', {bubbles: true, cancelable: true}));}); assert.equal(calls.filter(c => c.path === '/auth/otp/verify').length, 1); await act(async () => verification.resolve(response({error: 'OTP_INVALID', message: '验证码不正确，请重试'}, 400))); await flush(); assert.match(text(), /验证码不正确/); assert.equal(button('登录 / 注册').disabled, false); assert.equal(window.location.pathname, '/');});
await check('OTP resend replaces challenge and clears old code', async () => {let count = 0; await mount(ui.StoreLogin, call => call.path === '/session' ? response(anonymous()) : response({challengeId: 'synthetic-' + ++count, retryAfterSeconds: 0, expiresInSeconds: 300})); await input('#login-phone', '13800000000'); await click(button('获取验证码')); await input('#login-code', '111111'); await click(button('重新发送')); assert.equal(calls.filter(c => c.path === '/auth/otp/request').length, 2); assert.equal($('#login-code').value, ''); assert.equal(button('登录 / 注册').disabled, true);});
await check('Changing phone invalidates the prior challenge', async () => {await input('#login-phone', '13900000000'); assert.equal($('#login-code').disabled, true); assert.equal(button('登录 / 注册').disabled, true);});
await check('Server OTP rate limit prevents retries until its retry window passes', async () => {await mount(ui.StoreLogin, call => call.path === '/session' ? response(anonymous()) : response({error: 'RATE_LIMITED', message: '请求太频繁', retryAfterSeconds: 30}, 429)); await input('#login-phone', '13800000000'); await click(button('获取验证码')); assert.equal(button('30 秒后重发').disabled, true); now += 31_000; await act(async () => intervals.forEach(({fn}) => fn())); assert.equal(button('获取验证码').disabled, false);});
await check('Unmounting interrupted OTP aborts the in-flight request', async () => {const pending = deferred(); await mount(ui.StoreLogin, call => call.path === '/session' ? response(anonymous()) : pending.promise); await input('#login-phone', '13800000000'); await click(button('获取验证码')); const signal = calls.at(-1).init.signal; await act(async () => root.unmount()); root = null; assert.equal(signal.aborted, true); pending.resolve(response({challengeId: 'aborted', retryAfterSeconds: 60, expiresInSeconds: 300})); await flush();});

await check('Expired OTP cannot be verified and offers a new challenge', async () => {await mount(ui.StoreLogin, call => call.path === '/session' ? response(anonymous()) : response({challengeId: 'expiry-test', retryAfterSeconds: 30, expiresInSeconds: 60})); await input('#login-phone', '13800000000'); await click(button('获取验证码')); await input('#login-code', '000000'); now += 61_000; await act(async () => intervals.forEach(({fn}) => fn())); assert.match(text(), /验证码已过期/); assert.equal(button('登录 / 注册').disabled, true); assert.equal(button('重新发送').disabled, false); await submit(); assert.equal(calls.filter(c => c.path === '/auth/otp/verify').length, 0);});

await check('Guest checkout keeps exact selected style in login return link', async () => {await mount(ui.Checkout, () => response(anonymous()), '/checkout?style=black-coral'); const link = [...document.querySelectorAll('a')].find(a => a.textContent.includes('登录后继续')); assert.equal(link.getAttribute('href'), '/login?return_to=%2Fcheckout%3Fstyle%3Dblack-coral'); assert.equal($('#checkout-name'), null); noPaymentAction();});
await check('Unknown checkout style gives a recoverable empty state', async () => {await mount(ui.Checkout, checkoutMock(), '/checkout?style=unknown'); assert.match(text(), /先挑选一款/); assert.equal($('form'), null);});
await check('Standard price is 99 yuan per item; coupon preview capped at 30 and shipping unknown', async () => {await mount(ui.Checkout, checkoutMock({coupons: [couponFixture()]}), '/checkout?style=black-coral'); assert.match($('.store-product-summary').textContent, /¥99/); assert.match(text(), /预计抵扣 ¥30/); assert.match($('.store-summary-list').textContent, /待人工确认/); await input('#checkout-quantity', '2'); assert.match($('.store-summary-list').textContent, /¥198/); assert.equal(button('保存订单草稿').disabled, true); noPaymentAction();});
await check('Invalid quantities stay blocked and never become a zero-price checkout', async () => {for (const value of ['0', '1.5', '101', '']) {await input('#checkout-quantity', value); assert.equal(button('保存订单草稿').disabled, true, value); assert.match($('.store-summary-list').textContent, /待确认/);} });
await check('Order transport failure never reports success and preserves filled form', async () => {await mount(ui.Checkout, checkoutMock({post: () => response({error: 'ORDER_UNAVAILABLE', message: '合成服务器拒绝保存'}, 503)}), '/checkout?style=black-coral'); await fillAddress(); await submit(); await until(() => text().includes('合成服务器拒绝保存'), 'order rejection'); assert.doesNotMatch(text(), /订单草稿已保存/); assert.equal($('#checkout-name').value, '合成测试收货人'); assert.equal(button('保存订单草稿').disabled, false); noPaymentAction();});
await check('Order retry reuses idempotency key and pending repeated submits create one request', async () => {const keys = []; let pending; await mount(ui.Checkout, checkoutMock({post: call => {keys.push(call.body.operationKey); if (keys.length === 1) return response({error: 'RETRY', message: '合成重试错误'}, 503); pending = deferred(); return pending.promise;}}), '/checkout?style=black-coral'); await fillAddress(); await submit(); await until(() => keys.length === 1 && button('保存订单草稿').disabled === false, 'first request unlock'); await act(async () => {const form = $('form'); form.dispatchEvent(new window.Event('submit', {bubbles: true, cancelable: true})); form.dispatchEvent(new window.Event('submit', {bubbles: true, cancelable: true}));}); await until(() => keys.length === 2, 'second request'); assert.equal(keys[0], keys[1]); assert.equal(calls.filter(c => c.path === '/orders').length, 2); await act(async () => pending.resolve(response({order: orderFixture({kind: 'standard', goodsTotalFen: 9900, discountFen: 500, shippingFen: null})}))); await flush(); assert.match(text(), /订单草稿已保存/); assert.match(text(), /尚未付款、尚未排产/); assert.match(text(), /¥99/); assert.match(text(), /待确认（人工确认）/); assert.ok($('a[href="/my?order=order-synthetic"]')); noPaymentAction(); assert.equal(calls.find(c => c.path === '/orders').body.kind, 'standard');});
await check('Private standard custom design routes to 159 yuan and current saved version', async () => {let body; await mount(ui.Checkout, checkoutMock({post: call => {body = call.body; return response({order: orderFixture()});}}), '/checkout?design=design-synthetic'); assert.match($('.store-product-summary').textContent, /自由定制/); assert.match($('.store-summary-list').textContent, /¥159/); await fillAddress(); await submit(); await until(() => body, 'custom post'); assert.equal(body.kind, 'custom'); assert.equal(body.designId, 'design-synthetic'); assert.equal(body.designVersion, 3); assert.equal(body.useCoupons, true);});
await check('Custom artwork requires separate quote and cannot use coupons', async () => {const design = designFixture(); design.design.parts.body.art.push({id: 'art-test', kind: 'text', text: '合成图案', color: '#000000', x: 0.5, y: 0.5, scale: 1, rotation: 0}); let body; await mount(ui.Checkout, checkoutMock({design, coupons: [couponFixture()], post: call => {body = call.body; return response({order: orderFixture({kind: 'bespoke', goodsTotalFen: null, unitPriceFen: null})});}}), '/checkout?design=design-synthetic'); assert.match($('.store-product-summary').textContent, /特殊工艺询价/); assert.match($('.store-summary-list').textContent, /商家单独报价/); assert.equal($('.store-checkout-coupons'), null); await fillAddress(); await submit(); await until(() => body, 'bespoke post'); assert.equal(body.kind, 'bespoke'); assert.equal(body.useCoupons, false); assert.match(text(), /特殊工艺需要商家单独报价/); noPaymentAction();});
await check('Checkout finds spendable coupons beyond an expired first page', async () => {const base = checkoutMock(); await mount(ui.Checkout, call => {if (call.path === '/coupons') return response({coupons: [couponFixture({id: 'expired', spendableFen: 0, status: 'expired'})], pagination: {limit: 1, offset: 0, total: 2, hasMore: true}}); if (call.path === '/coupons?limit=100&offset=1') return response({coupons: [couponFixture({amountFen: 500, spendableFen: 500})], pagination: {limit: 100, offset: 1, total: 2, hasMore: false}}); return base(call);}, '/checkout?style=black-coral'); assert.match(text(), /预计抵扣 ¥5/); assert.equal($('.store-checkout-coupons input').disabled, false); assert.equal(calls.filter(c => c.path.startsWith('/coupons')).length, 2);});

await check('Unsupported design material preserves design but blocks order', async () => {const design = designFixture(); design.design.parts.body.material = 'suede'; await mount(ui.Checkout, checkoutMock({design}), '/checkout?design=design-synthetic'); await fillAddress(); assert.match(text(), /当前新订单仅支持细纹皮革/); assert.equal(button('保存订单草稿').disabled, true); assert.ok($('a[href="/customize?design=design-synthetic"]'));});

await check('Guest account has login and local-design recovery, without private endpoints', async () => {await mount(ui.Account, () => response(anonymous()), '/my'); assert.ok($('a[href="/login?return_to=%2Fmy"]')); assert.ok($('a[href="/customize?storage=local"]')); assert.deepEqual(calls.map(c => c.path), ['/session']);});
await check('Saved design is private and gallery opt-in requires a separate unchecked confirmation', async () => {let consent; await mount(ui.Account, accountMock({designs: [designFixture()], other: call => {consent = call.body; return response({design: designFixture({galleryConsent: true})});}}), '/my'); assert.match(text(), /仅自己可见/); assert.equal(button('授权本版作品展示').disabled, true); assert.equal($('.store-consent input[type="checkbox"]').checked, false); await click($('.store-consent input[type="checkbox"]')); await click(button('授权本版作品展示')); assert.deepEqual(consent, {version: 3, consent: true}); assert.match(text(), /已授权 · 待精选/);});
await check('Gallery consent withdrawal removes the visible public authorization state', async () => {await mount(ui.Account, accountMock({designs: [designFixture({galleryConsent: true, galleryPublished: true})], other: call => {assert.deepEqual(call.body, {version: 3, consent: false}); return response({design: designFixture()});}}), '/my'); await click(button('撤回本版展示授权')); assert.match(text(), /仅自己可见/); assert.doesNotMatch(text(), /已精选展示/);});
await check('Logout removes private account details and does not cache them in browser storage', async () => {let signedIn = true; await mount(ui.Account, accountMock({designs: [designFixture()], session: () => signedIn ? session() : anonymous(), other: call => {assert.equal(call.path, '/auth/logout'); signedIn = false; return response({ok: true});}}), '/my'); assert.match(text(), /合成私密设计/); await click(button('退出登录')); await until(() => text().includes('登录，找到你的专属空间'), 'guest after logout'); assert.doesNotMatch(text(), /合成私密设计|138\*\*\*\*0000/); assert.equal(localStorage.length, 0); assert.equal(sessionStorage.length, 0);});
await check('Material consent only confirms the latest rendered version after explicit agreement', async () => {let posted, updated; const order = orderFixture(); await mount(ui.OrderDetail, call => {posted = call.body; return response({order: {...order, acceptedMaterialVersion: 1}});}, '/my?order=order-synthetic', {order, onChange: value => {updated = value;}}); assert.equal(button('确认本版材料与设计').disabled, true); await click($('.store-material-review input[type="checkbox"]')); await click(button('确认本版材料与设计')); assert.deepEqual(posted, {version: 1}); assert.equal(updated.acceptedMaterialVersion, 1);});
await check('Material version replacement invalidates a checked prior-version consent', async () => {const order = orderFixture(); await mount(ui.OrderDetail, () => response({}), '/my', {order, onChange: () => {}}); await click($('.store-material-review input[type="checkbox"]')); await act(async () => root.render(React.createElement(ui.OrderDetail, {order: {...order, materialVersion: 2, materials: [...order.materials, {version: 2, note: '合成材料版本二', photoRefs: []}]}, onChange: () => {}}))); assert.equal($('.store-material-review input[type="checkbox"]').checked, false); assert.equal(button('确认本版材料与设计').disabled, true);});
await check('Stale material rejection refreshes order and requires a new consent', async () => {const original = orderFixture(); let newOrder; await mount(ui.OrderDetail, call => call.method === 'POST' ? response({error: 'STALE_MATERIAL', message: '材料版本已更新'}, 409) : response({order: {...original, materialVersion: 2, materials: [...original.materials, {version: 2, note: '版本二', photoRefs: []}]}}), '/my', {order: original, onChange: order => {newOrder = order;}}); await click($('.store-material-review input[type="checkbox"]')); await click(button('确认本版材料与设计')); assert.match(text(), /材料版本已更新/); assert.equal(newOrder.materialVersion, 2); assert.equal($('.store-material-review input[type="checkbox"]').checked, false); assert.equal(button('确认本版材料与设计').disabled, true);});

await check('Shipping quote requires explicit current-version consent', async () => {const order = orderFixture({shippingFen: 1200, shippingVersion: 2, shippingState: 'awaiting_customer_confirmation'}); let posted, updated; await mount(ui.OrderDetail, call => {posted = call; return response({order: {...order, shippingState: 'confirmed', acceptedShippingVersion: 2}});}, '/my', {order, onChange: value => {updated = value;}}); assert.equal(button('确认本版运费').disabled, true); const checkbox = button('确认本版运费').closest('section').querySelector('input[type="checkbox"]'); await click(checkbox); await click(button('确认本版运费')); assert.equal(posted.path, '/orders/order-synthetic/shipping/accept'); assert.deepEqual(posted.body, {version: 2}); assert.equal(updated.acceptedShippingVersion, 2); assert.match(text(), /已确认本版运费/);});
await check('Shipping quote changes invalidate already-checked earlier quote consent', async () => {const order = orderFixture({shippingFen: 1200, shippingVersion: 2, shippingState: 'awaiting_customer_confirmation'}); await mount(ui.OrderDetail, () => response({}), '/my', {order, onChange: () => {}}); await click(button('确认本版运费').closest('section').querySelector('input[type="checkbox"]')); await act(async () => root.render(React.createElement(ui.OrderDetail, {order: {...order, shippingFen: 1800, shippingVersion: 3}, onChange: () => {}}))); assert.equal(button('确认本版运费').disabled, true); assert.equal(button('确认本版运费').closest('section').querySelector('input[type="checkbox"]').checked, false); assert.match(text(), /本版运费：¥18/);});
await check('Bespoke quote is separate from shipping and requires explicit latest-version acceptance', async () => {const order = orderFixture({kind: 'bespoke', unitPriceFen: 25000, goodsTotalFen: 50000, quantity: 2, quoteVersion: 3, discountFen: 0}); let posted, updated; await mount(ui.OrderDetail, call => {posted = call; return response({order: {...order, acceptedQuoteVersion: 3}});}, '/my', {order, onChange: value => {updated = value;}}); assert.match(text(), /单价 ¥250 × 2 件，商品总额 ¥500/); assert.match(text(), /本报价不使用优惠券，运费单独确认/); assert.equal(button('确认本版报价').disabled, true); await click(button('确认本版报价').closest('section').querySelector('input')); await click(button('确认本版报价')); await until(() => updated, 'bespoke quote acceptance'); assert.equal(posted.path, '/orders/order-synthetic/quote/accept'); assert.equal(posted.body.version, 3); assert.equal(posted.body.useCoupons, false); assert.match(posted.body.operationKey, /^[0-9a-f-]{36}$/); assert.equal(updated.acceptedQuoteVersion, 3); assert.match(text(), /已确认本版特殊工艺报价/); noPaymentAction();});
await check('New bespoke quote invalidates earlier checkbox consent', async () => {const order = orderFixture({kind: 'bespoke', unitPriceFen: 25000, goodsTotalFen: 25000, quoteVersion: 3}); await mount(ui.OrderDetail, () => response({}), '/my', {order, onChange: () => {}}); await click(button('确认本版报价').closest('section').querySelector('input')); await act(async () => root.render(React.createElement(ui.OrderDetail, {order: {...order, quoteVersion: 4, unitPriceFen: 30000, goodsTotalFen: 30000}, onChange: () => {}}))); assert.equal(button('确认本版报价').disabled, true); assert.equal(button('确认本版报价').closest('section').querySelector('input').checked, false); assert.match(text(), /商品总额 ¥300/);});
await check('Stale bespoke quote error refreshes the order and cannot claim acceptance', async () => {const order = orderFixture({kind: 'bespoke', unitPriceFen: 25000, goodsTotalFen: 25000, quoteVersion: 3}); let updated; await mount(ui.OrderDetail, call => call.method === 'POST' ? response({error: 'STALE_VERSION', message: '合成报价已更新'}, 409) : response({order: {...order, quoteVersion: 4, unitPriceFen: 30000, goodsTotalFen: 30000}}), '/my', {order, onChange: value => {updated = value;}}); await click(button('确认本版报价').closest('section').querySelector('input')); await click(button('确认本版报价')); await until(() => updated, 'stale bespoke quote refresh'); assert.match(text(), /合成报价已更新/); assert.doesNotMatch(text(), /已确认本版特殊工艺报价/); assert.equal(updated.quoteVersion, 4); assert.equal(button('确认本版报价').disabled, true);});

await check('Cancel dialog can be dismissed without changing the order', async () => {await mount(ui.OrderDetail, () => response({}), '/my', {order: orderFixture(), onChange: () => {}}); await click(button('取消未付款订单')); assert.match(text(), /确认取消这份未付款订单/); await click(button('保留订单')); assert.equal(buttons('确认取消订单').length, 0); assert.ok(button('取消未付款订单')); assert.equal(calls.length, 0);});
await check('Confirmed unpaid cancellation sends one idempotent mutation and updates its status', async () => {let pending, updated; await mount(ui.OrderDetail, () => {pending = deferred(); return pending.promise;}, '/my', {order: orderFixture(), onChange: value => {updated = value;}}); await click(button('取消未付款订单')); const confirm = button('确认取消订单'); await act(async () => {confirm.click(); confirm.click();}); await until(() => pending, 'cancel request'); assert.equal(calls.length, 1); assert.equal(calls[0].path, '/orders/order-synthetic/cancel'); assert.match(calls[0].body.operationKey, /^[0-9a-f-]{36}$/); await act(async () => pending.resolve(response({order: orderFixture({status: 'cancelled'})}))); await flush(); assert.equal(updated.status, 'cancelled'); assert.match(text(), /订单已取消/);});
await check('Paid orders cannot offer unpaid cancellation; terminal orders cannot offer consent', async () => {await mount(ui.OrderDetail, () => response({}), '/my', {order: orderFixture({paidAt: '2026-09-30T00:00:00Z', status: 'ready_for_production'}), onChange: () => {}}); assert.equal(buttons('取消未付款订单').length, 0); await mount(ui.OrderDetail, () => response({}), '/my', {order: orderFixture({status: 'cancelled', shippingFen: 500, shippingVersion: 1}), onChange: () => {}}); assert.equal(buttons('取消未付款订单').length, 0); assert.equal(buttons('确认本版材料与设计').length, 0); assert.equal(buttons('确认本版运费').length, 0);});
await check('Direct order link loads freshest full order even outside list page', async () => {const fresh = orderFixture({materialVersion: 7, materials: [{version: 7, note: '合成最新第七版材料', photoRefs: []}]}); await mount(ui.Account, accountMock({orders: [], other: call => {assert.equal(call.path, '/orders/order-synthetic'); return response({order: fresh});}}), '/my?order=order-synthetic'); assert.match(text(), /合成最新第七版材料/); assert.match(text(), /第 7 版/); assert.equal(calls.filter(c => c.path === '/orders/order-synthetic').length, 1); assert.equal(button('确认本版材料与设计').disabled, true);});
await check('Order detail ownership failure stays unavailable instead of using list data', async () => {await mount(ui.Account, accountMock({orders: [orderFixture()], other: () => response({error: 'NOT_FOUND', message: '合成订单不存在或不可访问'}, 404)}), '/my?order=order-synthetic'); assert.match(text(), /合成订单不存在或不可访问/); assert.equal($('.store-order-detail'), null);});
await check('Account navigation aborts pending detail and ignores a superseded response', async () => {const pending = deferred(); await mount(ui.Account, accountMock({orders: [orderFixture()], other: () => pending.promise}), '/my?order=order-synthetic'); const detailRequest = calls.find(c => c.path === '/orders/order-synthetic'); assert.ok(detailRequest); await click(button('返回全部订单')); assert.equal(detailRequest.init.signal.aborted, true); await act(async () => pending.resolve(response({order: orderFixture()}))); await flush(); assert.equal($('.store-order-detail'), null); assert.ok($('.store-order-row'));});

await check('Paginated account designs append once and remain complete after tab navigation', async () => {const base = accountMock(); const first = designFixture({id: 'design-1', name: '合成分页一'}), second = designFixture({id: 'design-2', name: '合成分页二'}); await mount(ui.Account, call => {if (call.path === '/designs') return response({designs: [first], pagination: {limit: 1, offset: 0, total: 2, hasMore: true}}); if (call.path === '/designs?limit=1&offset=1') return response({designs: [second], pagination: {limit: 1, offset: 1, total: 2, hasMore: false}}); return base(call);}, '/my'); await click(button('加载更多')); assert.equal(document.querySelectorAll('.store-design-card').length, 2); assert.equal(buttons('加载更多').length, 0); await click(button('我的订单')); await click(button('我的设计')); assert.equal(document.querySelectorAll('.store-design-card').length, 2); assert.equal(buttons('加载更多').length, 0, 'Completed page must not reload previously appended rows after tab return');});
await check('Login close aborts pending verification and retains the safe return destination', async () => {const pending = deferred(); await mount(ui.StoreLogin, call => {if (call.path === '/session') return response(anonymous()); if (call.path === '/auth/otp/request') return response({challengeId: 'close-test', retryAfterSeconds: 0, expiresInSeconds: 300}); return pending.promise;}, '/login?return_to=%2Fcheckout%3Fstyle%3Dblack-coral'); await input('#login-phone', '13800000000'); await click(button('获取验证码')); await input('#login-code', '000000'); await submit(); const verify = calls.find(call => call.path === '/auth/otp/verify'); const close = $('.store-close'); assert.equal(close.getAttribute('href'), '/checkout?style=black-coral'); close.addEventListener('click', event => event.preventDefault(), {once: true}); await click(close); assert.equal(verify.init.signal.aborted, true); await act(async () => pending.resolve(response({error: 'OTP_INVALID', message: '合成已终止验证码'}, 400))); await flush(); assert.doesNotMatch(text(), /合成已终止验证码/);});

await check('Unauthenticated admin has only a login route and no privileged reads', async () => {await mount(ui.Admin, () => response(anonymous()), '/admin'); assert.match(text(), /请使用商家账号登录/); assert.ok($('a[href="/login?return_to=%2Fadmin"]')); assert.deepEqual(calls.map(c => c.path), ['/session']);});
await check('Customer role receives admin denial without reading privileged data', async () => {await mount(ui.Admin, () => response(session()), '/admin'); assert.match(text(), /当前账号没有商家管理权限/); assert.deepEqual(calls.map(c => c.path), ['/session']); assert.equal($('.store-tabs'), null);});
await check('Admin endpoint 403 shows truthful service denial and no management controls', async () => {await mount(ui.Admin, call => call.path === '/session' ? response(session({user: {...user, role: 'admin'}})) : response({error: 'FORBIDDEN', message: '合成权限被撤销'}, 403), '/admin'); assert.match(text(), /合成权限被撤销/); assert.equal($('.store-admin-order'), null); assert.equal($('#coupon-user'), null); noPaymentAction();});
await check('Admin unpaid order cannot start production, dispatch, or mark payment', async () => {await mount(ui.Admin, adminMock({orders: [orderFixture()]}), '/admin?order=order-synthetic'); assert.match(text(), /尚未满足排产或发货条件/); assert.equal(buttons('记录开始制作').length, 0); assert.equal($('#carrier'), null); assert.equal(buttons('保存第 2 版并请客户确认')[0].disabled, true); noPaymentAction();});
await check('Admin shipping quote uses fen and pending repeated submit has one action', async () => {const pending = deferred(), initial = orderFixture(); await mount(ui.Admin, adminMock({orders: [initial], other: () => pending.promise}), '/admin?order=order-synthetic'); await input('#shipping-quote', '12.34'); await input('#shipping-note', '合成快递报价'); const form = $('#shipping-quote').closest('form'); await act(async () => {form.dispatchEvent(new window.Event('submit', {bubbles: true, cancelable: true})); form.dispatchEvent(new window.Event('submit', {bubbles: true, cancelable: true}));}); const posts = calls.filter(c => c.method === 'POST'); assert.equal(posts.length, 1); assert.equal(posts[0].path, '/admin/orders/order-synthetic/shipping'); assert.equal(posts[0].body.shippingFen, 1234); await act(async () => pending.resolve(response({order: {...initial, shippingFen: 1234, shippingVersion: 1, shippingState: 'awaiting_customer_confirmation'}}))); await flush(); assert.match(text(), /¥12.34/); assert.match(text(), /等待客户确认/); noPaymentAction();});
await check('Admin bespoke quote posts exact unit price and displays multiplied goods total', async () => {const order = orderFixture({kind: 'bespoke', unitPriceFen: null, goodsTotalFen: null, discountFen: 0, quantity: 2}); let posted; await mount(ui.Admin, adminMock({orders: [order], other: call => {posted = call; return response({order: {...order, unitPriceFen: call.body.unitPriceFen, goodsTotalFen: call.body.unitPriceFen * 2, quoteVersion: 1}});}}), '/admin?order=order-synthetic'); await input('#bespoke-quote', '250.25'); assert.match(text(), /商品报价合计 ¥500.50/); await act(async () => $('#bespoke-quote').closest('form').dispatchEvent(new window.Event('submit', {bubbles: true, cancelable: true}))); await flush(); assert.equal(posted.path, '/admin/orders/order-synthetic/quote'); assert.deepEqual(posted.body, {unitPriceFen: 25025}); assert.match(text(), /特殊工艺报价已保存，等待客户确认/); assert.match(text(), /¥500.50/); noPaymentAction();});
await check('Admin cannot overwrite a customer-accepted bespoke quote', async () => {await mount(ui.Admin, adminMock({orders: [orderFixture({kind: 'bespoke', quoteVersion: 2, acceptedQuoteVersion: 2})]}), '/admin?order=order-synthetic'); assert.equal($('#bespoke-quote'), null); assert.equal(buttons('保存报价并请客户确认').length, 0);});

await check('Admin rejected production action does not claim production started', async () => {await mount(ui.Admin, adminMock({orders: [orderFixture({status: 'ready_for_production', paidAt: '2026-09-30T00:00:00Z', acceptedMaterialVersion: 1})], other: () => response({error: 'MATERIAL_CHANGED', message: '合成最新材料待确认'}, 409)}), '/admin?order=order-synthetic'); await click(button('记录开始制作')); assert.match(text(), /合成最新材料待确认/); assert.doesNotMatch(text(), /已记录开始制作/); assert.equal($('#carrier'), null);});
await check('Admin dispatch preserves carrier and tracking only after server acceptance', async () => {const initial = orderFixture({status: 'in_production', paidAt: '2026-09-30T00:00:00Z', acceptedMaterialVersion: 1}); let posted; await mount(ui.Admin, adminMock({orders: [initial], other: call => {posted = call.body; return response({order: {...initial, status: 'shipped', shipment: {carrier: posted.carrier, tracking: posted.tracking, dispatchedAt: '2026-09-30T00:00:00Z'}}});}}), '/admin?order=order-synthetic'); await input('#carrier', '合成快递'); await input('#tracking', 'SYNTHETIC-TRACK-123'); await act(async () => $('#carrier').closest('form').dispatchEvent(new window.Event('submit', {bubbles: true, cancelable: true}))); await flush(); assert.deepEqual(posted, {carrier: '合成快递', tracking: 'SYNTHETIC-TRACK-123'}); assert.match(text(), /发货记录已保存/); assert.match(text(), /SYNTHETIC-TRACK-123/); assert.equal($('#carrier'), null);});
await check('Admin gallery curation failure leaves authorization candidate unpublished', async () => {const candidate = {designId: 'design-synthetic', version: 3, published: false, design: {name: '合成配色', parts: {body: {color: '#abcdef'}, corner0: {color: '#abcdef'}, trim: {color: '#abcdef'}}}}; await mount(ui.Admin, adminMock({designs: [candidate], other: () => response({error: 'CONSENT_WITHDRAWN', message: '合成授权已撤回'}, 409)}), '/admin'); await click(button('作品精选')); await click(button('选入公开作品集')); assert.match(text(), /合成授权已撤回/); assert.equal(button('选入公开作品集').disabled, false); assert.equal(buttons('从作品集下架').length, 0);});
await check('Admin coupon revocation cancel closes form without mutation', async () => {await mount(ui.Admin, adminMock({coupons: [couponFixture()]}), '/admin'); await click(button('优惠券')); await click(button('停用此券')); await input('#revoke-coupon-synthetic', '合成原因'); await click(button('取消')); assert.equal($('#revoke-coupon-synthetic'), null); assert.equal(calls.filter(c => c.method === 'POST').length, 0); assert.ok(button('停用此券'));});
await check('Admin coupon grant converts yuan to fen and keeps duplicate pending grants singular', async () => {const pending = deferred(); await mount(ui.Admin, adminMock({other: () => pending.promise}), '/admin'); await click(button('优惠券')); await input('#coupon-user', 'synthetic-customer'); await input('#coupon-amount', '5.25'); await input('#coupon-expires', '2027-12-01'); await input('#coupon-reason', '合成测试活动'); const form = $('#coupon-user').closest('form'); await act(async () => {form.dispatchEvent(new window.Event('submit', {bubbles: true, cancelable: true})); form.dispatchEvent(new window.Event('submit', {bubbles: true, cancelable: true}));}); await until(() => calls.some(c => c.method === 'POST'), 'coupon mutation'); const posted = calls.filter(c => c.method === 'POST'); assert.equal(posted.length, 1); assert.equal(posted[0].path, '/admin/coupons'); assert.equal(posted[0].body.amountFen, 525); assert.equal(posted[0].body.expiresAt, '2027-12-01T15:59:59.000Z'); assert.equal(posted[0].body.reason, '合成测试活动'); await act(async () => pending.resolve(response({coupon: couponFixture({amountFen: 525})}))); await until(() => text().includes('优惠券已发放'), 'coupon success'); assert.match(text(), /¥5.25/);});
await check('Admin rejects unsupported material-photo types without an upload request', async () => {await mount(ui.Admin, adminMock({orders: [orderFixture()]}), '/admin?order=order-synthetic'); const photo = $('#material-photos'); Object.defineProperty(photo, 'files', {value: [{name: 'synthetic.svg', type: 'image/svg+xml', size: 100}], configurable: true}); await act(async () => photo.dispatchEvent(new window.Event('change', {bubbles: true}))); await flush(); assert.match(text(), /8 MB 以内的 JPG、PNG 或 WebP/); assert.equal(calls.filter(c => c.method === 'POST').length, 0); assert.equal(button('保存第 2 版并请客户确认').disabled, true);});

await check('Private photos use credentialed requests and revoke blob URLs on unmount', async () => {const previousCreate = URL.createObjectURL, previousRevoke = URL.revokeObjectURL; const revoked = []; URL.createObjectURL = () => 'blob:synthetic-photo'; URL.revokeObjectURL = value => revoked.push(value); try {await mount(ui.PrivatePhoto, call => {assert.equal(call.path, '/objects/photo-synthetic'); assert.equal(call.init.credentials, 'same-origin'); return new Response(new Uint8Array([1, 2, 3]), {headers: {'content-type': 'image/png'}});}, '/my', {photoId: 'photo-synthetic', alt: '合成私密材料照片'}); assert.equal($('.store-private-photo').getAttribute('src'), 'blob:synthetic-photo'); assert.equal($('.store-private-photo').alt, '合成私密材料照片'); const signal = calls[0].init.signal; await act(async () => root.unmount()); root = null; assert.deepEqual(revoked, ['blob:synthetic-photo']); assert.equal(signal.aborted, true);} finally {URL.createObjectURL = previousCreate; URL.revokeObjectURL = previousRevoke;}});

await check('Public gallery reads only public endpoint and never renders private fields or uploads', async () => {await mount(ui.Gallery, call => {assert.equal(call.path, '/gallery'); return response({gallery: [{id: 'public-1', version: 1, design: {name: '公开合成配色', parts: {body: {color: '#aabbcc', edge: '#334455'}, corner0: {color: '#abcdef'}, trim: {color: '#123456'}}, phone: 'PRIVATE-PHONE-SENTINEL', address: 'PRIVATE-ADDRESS-SENTINEL', art: [{src: 'https://private.example.test/secret.png'}]}}]});}, '/gallery'); assert.match(text(), /公开合成配色/); assert.doesNotMatch(text(), /PRIVATE-/); assert.equal(document.querySelectorAll('.store-gallery-card img').length, 0); assert.match(text(), /保存设计不会自动出现在这里/); assert.equal(calls.length, 1);});
await check('Public gallery empty and failed states are recoverable without synthetic examples', async () => {await mount(ui.Gallery, () => response({gallery: []}), '/gallery'); assert.match(text(), /暂时没有已授权并上架/); assert.equal($('.store-gallery-card'), null); await mount(ui.Gallery, () => response({error: 'SERVICE_UNAVAILABLE', message: '合成作品服务不可用'}, 503), '/gallery'); assert.match(text(), /合成作品服务不可用/); assert.equal($('.store-gallery-card'), null); assert.equal(button('重试连接').disabled, false);});
await check('Checkout form labels, error alerts, skip link and landmark are usable', async () => {await mount(ui.Checkout, checkoutMock(), '/checkout?style=black-coral'); for (const el of document.querySelectorAll('input,textarea')) assert.ok(el.closest('label') || document.querySelector(`label[for="${el.id}"]`), `label for ${el.id}`); assert.ok($('main#store-main')); assert.ok($('a[href="#store-main"]')); await fillAddress(); await input('#checkout-phone', '123'); await submit(); assert.match($('[role="alert"]').textContent, /正确的中国大陆/);});

if (root) await act(async () => root.unmount());
await flush();
await check('All login timers are removed when their pages unmount', () => assert.equal(intervals.size, 0));
const result = {date: new Date().toISOString(), result: failed.length ? 'FAIL' : 'PASS', passed: pass.length, failed: failed.length, tests: pass, failures: failed, limits: ['DOM interaction tests with synthetic sessions and mock network only. No SMS, real credentials, payment, deployment or live provider was used.', 'No screenshot or real-browser rendering verification: provided environment blocks Chromium sockets and CUA loopback navigation.']};
const reportPath = process.env.STORE_UI_REPORT || path.join(os.tmpdir(), 'dlcj-store-ui-results.json');
fs.writeFileSync(reportPath, JSON.stringify(result, null, 2) + '\n');
console.log(`\n${pass.length} passed; ${failed.length} failed. Report: ${reportPath}`);
Date.now = realDateNow; globalThis.clearInterval = realClearInterval;
dom.window.close(); fs.rmSync(tmp, {recursive: true, force: true});
process.exitCode = failed.length ? 1 : 0;
