import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
const repo=path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const requireQA=createRequire(path.join(process.env.STORE_UI_QA_DIR || repo, 'package.json'));
const {build}=requireQA('esbuild');
const {JSDOM}=requireQA('jsdom');
const {indexedDB,IDBKeyRange}=requireQA('fake-indexeddb');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'dlcj-studio-qa-'));
const bundle=path.join(tmp,'ui.mjs');
await build({stdin:{contents:`export {default as Studio} from './components/studio'; export {localDesignRequest} from './netlify-browser/local-design-api'; export {initialDesign} from './lib/design'; export {designSchema} from './lib/schema'; export {loadDraft} from './lib/draft'; export {createRoot} from 'react-dom/client'; export {createElement,act} from 'react';`,resolveDir:repo,loader:'tsx'},outfile:bundle,bundle:true,format:'esm',platform:'browser',define:{'process.env.NODE_ENV':'"test"'},logLevel:'silent'});
const dom=new JSDOM('<!doctype html><html><body><div id="root"></div></body></html>',{url:'https://qa.example.test/customize',pretendToBeVisual:true});
for(const key of ['window','document','HTMLElement','HTMLInputElement','HTMLTextAreaElement','HTMLSelectElement','Element','Node','DocumentFragment','MutationObserver','CustomEvent','MouseEvent','Event','KeyboardEvent','HTMLAnchorElement'])globalThis[key]=dom.window[key];
for(const key of Object.getOwnPropertyNames(dom.window)){if(/^[A-Z]/.test(key)&&!(key in globalThis))globalThis[key]=dom.window[key];}
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
globalThis.getComputedStyle=dom.window.getComputedStyle;
globalThis.localStorage=dom.window.localStorage;
globalThis.indexedDB=indexedDB;globalThis.IDBKeyRange=IDBKeyRange;
globalThis.requestAnimationFrame=fn=>setTimeout(()=>fn(Date.now()),0);globalThis.cancelAnimationFrame=clearTimeout;
globalThis.ResizeObserver=class{observe(){}unobserve(){}disconnect(){}};
window.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){},addListener(){},removeListener(){}});
window.HTMLElement.prototype.scrollIntoView=()=>{};
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const api=await import(pathToFileURL(bundle).href);
const {Studio,localDesignRequest,initialDesign,designSchema,loadDraft,createRoot,createElement:h,act}=api;
const downloads=[];HTMLAnchorElement.prototype.click=function(){downloads.push({href:this.href,name:this.download})};const nativeFetch=globalThis.fetch;
const results=[];let root=createRoot(document.getElementById('root'));
const record=(name,condition=true)=>{assert(condition,name);results.push(name)};
const flush=()=>act(async()=>{await new Promise(resolve=>setTimeout(resolve,30))});
const click=async el=>{assert(el,'button found');await act(async()=>el.click());await flush()};
const button=(text)=>[...document.querySelectorAll('button')].find(b=>b.textContent.replace(/\s+/g,' ').trim()===text||b.getAttribute('aria-label')===text);
const input=async(el,value)=>{await act(async()=>{Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,'value').set.call(el,value);el.dispatchEvent(new window.Event('input',{bubbles:true}));});await flush()};
const close=async()=>{const dialog=document.querySelector('[role="dialog"]');const x=[...dialog.querySelectorAll('button')].find(b=>b.textContent.trim()==='Close');if(x)await click(x);else await act(async()=>document.dispatchEvent(new window.KeyboardEvent('keydown',{key:'Escape',bubbles:true})));await flush()};
let saveCalls=0; const countedRequest=async(input,init)=>{if(init?.method==='POST')saveCalls++;return localDesignRequest(input,init)};
let networkCalls=0;globalThis.fetch=async(url)=>{if(String(url)==='/api/store/pricing')return Response.json({pricing:{currency:'CNY',version:1,standardFen:9900,customFen:15900,updatedAt:'2026-10-03T00:00:00Z'}});networkCalls++;throw new Error('No private design network expected in local storage')};
try{
 // IndexedDB adapter exercises real transaction semantics with the maintained IndexedDB polyfill.
 const design=initialDesign();design.name='QA adapter saved';design.parts.body.material='suede';
 const response=await localDesignRequest('/api/designs',{method:'POST',body:JSON.stringify(design)});record('local save returns 200',response.status===200);const saved=await response.json();
 const loaded=await(await localDesignRequest('/api/designs?id='+saved.id)).json();assert.deepEqual(loaded.design,design);record('all design details preserved through IndexedDB');
 const list=await(await localDesignRequest('/api/designs')).json();record('library lists saved record',list.designs.some(d=>d.id===saved.id));
 record('missing design returns 404',(await localDesignRequest('/api/designs?id=11111111-1111-4111-8111-111111111111')).status===404);
 record('invalid id rejected',(await localDesignRequest('/api/designs?id=../bad')).status===400);
 record('nonlocal target rejected',(await localDesignRequest('https://elsewhere.example/api/designs')).status===400);
 record('unsupported method rejected',(await localDesignRequest('/api/designs',{method:'DELETE'})).status===405);
 record('invalid schema rejected',(await localDesignRequest('/api/designs',{method:'POST',body:JSON.stringify({...design,name:''})})).status===400);
 const oldDb=globalThis.indexedDB;globalThis.indexedDB={open(){throw new Error('Quota/disabled')}};
 record('storage unavailable reports 503',(await localDesignRequest('/api/designs')).status===503);globalThis.indexedDB=oldDb;
 record('design storage makes zero network requests',networkCalls===0);
 // Real component render in a DOM environment, using the intentionally supported light mode.
 await act(async()=>root.render(h(Studio,{lightPreview:true,localOnly:true,designRequest:countedRequest})));await flush();
 record('light preview renders usable studio',document.body.textContent.includes('设计你的纸巾盒'));
 record('editor returns to tissue-box collection',document.querySelector('.dc-logo').getAttribute('href')==='/'&&document.querySelector('.studio-toolbarTitle a').getAttribute('href')==='/tissue-box');
 record('custom 159 pricing visible',document.body.textContent.includes('159'));
 record('new material picker offers only grain',!!document.querySelector('button[aria-label="细纹皮革"]')&&!document.querySelector('button[aria-label="光面皮革"]')&&!document.querySelector('button[aria-label="绒面质感"]'));
 record('colour picker explains approximate stock match',document.body.textContent.includes('按现有皮料近似匹配'));
 await click(document.querySelector('button[aria-label="保存设计"]'));
 record('local save disclosure visible',document.body.textContent.includes('仅保存在此设备的当前浏览器'));
 await input(document.querySelector('#designName'),'QA 本机保存');const saveButton=button('保存到我的设计');await act(async()=>{saveButton.click();saveButton.click()});await flush();record('rapid repeated save writes once',saveCalls===1);
 record('named save success UI',document.body.textContent.includes('已保存到当前浏览器'));
 await input(document.querySelector('#designName'),'QA 重命名');record('renaming clears old saved state',Boolean(button('保存到我的设计')));
 await click(button('保存到我的设计'));await close();
 await click(document.querySelector('button[aria-label="我的设计"]'));record('saved design appears in library',document.querySelector('.saved-list')?.textContent.includes('QA 重命名'));
 await click([...document.querySelectorAll('.saved-list button')].find(b=>b.textContent.includes('QA 重命名')));record('saved design restores name',document.querySelector('.stage-badge')?.textContent.includes('QA 重命名'));
 await click(document.querySelector('button[aria-label="保存设计"]'));await input(document.querySelector('#designName'),'');
 record('blank name disables save',button('保存到我的设计').disabled);
 await act(async()=>{await new Promise(resolve=>setTimeout(resolve,650))});const draft=await loadDraft();record('blank name cannot corrupt autosaved draft',designSchema.safeParse(draft).success&&draft.name==='QA 重命名');await close();
 await click(button('确认方案 · 咨询'));await input(document.querySelector('#consultQuantity'),'0');record('zero quantity blocks inquiry',button('复制需求文字').disabled);
 await input(document.querySelector('#consultQuantity'),'12');record('valid quantity enables inquiry',!button('复制需求文字').disabled);
 record('inquiry contains selected quantity',document.querySelector('.consult-output').value.includes('数量：12 件'));
 await close();await click(button('导出我的方案'));record('PNG safely unavailable in light preview',[...document.querySelectorAll('.export-option')][0].disabled);record('JSON remains available in light preview',![...document.querySelectorAll('.export-option')][1].disabled);await click([...document.querySelectorAll('.export-option')][1]);const exported=await(await nativeFetch(downloads.at(-1).href)).json();record('JSON download contains editable valid design',designSchema.safeParse(exported.design).success);await close();
 await act(async()=>root.unmount());root=createRoot(document.getElementById('root'));
 await act(async()=>root.render(h(Studio,{lightPreview:true,localOnly:true,designRequest:countedRequest})));await flush();record('draft survives component reload',document.querySelector('.stage-badge')?.textContent.includes('QA 重命名'));
 await click(button('确认方案 · 咨询'));record('inquiry quantity survives component reload',document.querySelector('#consultQuantity').value==='12');await close();
 const importData={type:'dlcj-inquiry-draft',version:1,design:{...initialDesign(),name:'QA imported inquiry'},request:{quantity:7,note:'QA note restored'}};const text=JSON.stringify(importData);const importer=document.querySelector('input[accept="application/json,.json"]');Object.defineProperty(importer,'files',{value:[{size:text.length,text:async()=>text}],configurable:true});await act(async()=>importer.dispatchEvent(new window.Event('change',{bubbles:true})));await flush();record('inquiry JSON imports editable design',document.querySelector('.stage-badge').textContent.includes('QA imported inquiry'));await click(button('确认方案 · 咨询'));record('inquiry JSON restores quantity and notes',document.querySelector('#consultQuantity').value==='7'&&document.querySelector('#consultNote').value==='QA note restored');await close();
 await act(async()=>root.unmount());root=createRoot(document.getElementById('root'));
 let returnedToProducts=false;const beforeInline=await loadDraft();
 await act(async()=>root.render(h(Studio,{lightPreview:true,localOnly:true,designRequest:countedRequest,embedded:true,onBack:()=>{returnedToProducts=true;}})));await flush();
 record('inline studio has no duplicate site header or main',!document.querySelector('.dc-siteHeader')&&!document.querySelector('main')&&!!document.querySelector('section.studio-embedded'));
 record('inline studio restores the existing local draft',document.querySelector('.stage-badge').textContent.includes(beforeInline.name));
 await click(document.querySelector('button[aria-label="保存设计"]'));await input(document.querySelector('#designName'),'QA inline latest');await close();
 await act(async()=>document.querySelector('.studio-toolbarTitle a[href="#choose-style"]').dispatchEvent(new window.MouseEvent('click',{bubbles:true,cancelable:true})));await flush();
 const inlineDraft=await loadDraft();record('returning to products saves the draft before closing',returnedToProducts&&inlineDraft.name==='QA inline latest');
 record('no local-storage network calls during UI flows',networkCalls===0);
 await act(async()=>root.unmount());
 fs.writeFileSync(path.join(os.tmpdir(),'dlcj-studio-regression-results.json'),JSON.stringify({passed:results.length,tests:results,limitations:['JSDOM plus fake-indexeddb, not real-browser visual/WebGL verification']},null,2));
 console.log(JSON.stringify({passed:results.length,tests:results},null,2));
}catch(error){console.error('FAILED AFTER',results);console.error(document.body.innerHTML.slice(0,2200));throw error;}finally{dom.window.close();fs.rmSync(tmp,{recursive:true,force:true})}

process.exit(0);
