import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {designSchema} from '@/lib/schema';
export const dynamic='force-dynamic';
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
async function access(){const user=await getChatGPTUser();if(!user)return null;return {bucket:(env as unknown as {BUCKET:R2Bucket}).BUCKET,prefix:`designs/${encodeURIComponent(user.userId)}/`};}
export async function GET(req:Request){try{const a=await access();if(!a)return json({error:'请登录后查看已保存的设计。'},401);const url=new URL(req.url),id=url.searchParams.get('id');if(id){if(!/^[a-f0-9-]{36}$/.test(id))return json({error:'方案编号无效。'},400);const obj=await a.bucket.get(a.prefix+id+'.json');if(!obj)return json({error:'没有找到这份设计。'},404);return json(await obj.json());}const list=await a.bucket.list({prefix:a.prefix,limit:100,include:['customMetadata']} as R2ListOptions & {include:string[]});return json({designs:list.objects.map(o=>({id:o.key.split('/').pop()!.replace('.json',''),name:o.customMetadata?.name??'未命名设计',date:o.uploaded.toISOString()})).sort((a,b)=>b.date.localeCompare(a.date))});}catch(e){console.error('Design read failed',e);return json({error:'暂时无法读取设计，请稍后重试。'},503);}}
export async function POST(req:Request){try{if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return json({error:'请求来源无效。'},403);const a=await access();if(!a)return json({error:'请登录后保存设计。'},401);if(Number(req.headers.get('content-length')??0)>12000000)return json({error:'设计素材过大，请减少图片后重试。'},413);const text=await req.text();if(text.length>12000000)return json({error:'设计素材过大。'},413);let parsed;try{parsed=designSchema.safeParse(JSON.parse(text));}catch{return json({error:'设计文件无法读取。'},400);}if(!parsed.success)return json({error:'设计数据不完整或素材超出限制。'},400);const id=crypto.randomUUID(),date=new Date().toISOString();await a.bucket.put(a.prefix+id+'.json',JSON.stringify({id,date,design:parsed.data}),{httpMetadata:{contentType:'application/json'},customMetadata:{name:parsed.data.name}});return json({id,date});}catch(e){console.error('Design save failed',e);return json({error:'保存暂时失败，当前设计仍保留在页面上。请重试或下载方案文件。'},503);}}

